/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Lau
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private dao.FuncionarioDAO dao = new dao.FuncionarioDAO();
    public VentanaPrincipal() {
        initComponents();
        CargarTabla();
    }
    
    private void CargarTabla() {
        String[] columnas = {"ID", "Cedula", "Nombre", "Apellido", "Email", "Telefono", "Fecha Ingreso"};
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0);
        try {
            for (modelo.Funcionario f : dao.listarTodos()) {
                modelo.addRow(new Object[]{
                    f.getId(), f.getCedula(), f.getNombre(), f.getApellido(),
                    f.getEmail(), f.getTelefono(), f.getFechaIngreso()});
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar: " + e.getMessage());
        }
        tablaDatos.setModel(modelo);
    }
    
    // Obtiene el ID del funcionario seleccionado en la tabla
    private int getIdSeleccionado() {
        int fila = tablaDatos.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un funcionario de la tabla.");
            return -1;
        }
        return (int) tablaDatos.getValueAt(fila, 0);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Gestion Funcionarios");

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaDatos.setToolTipText("Tabla de datos");
        jScrollPane1.setViewportView(tablaDatos);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(btnNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnActualizar))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        // Pedimos los datos con cuadros de diálogo simples
        String cedula = javax.swing.JOptionPane.showInputDialog(this, "Cedula:");
        if (cedula == null || cedula.isEmpty()) return;
        
        String nombre = javax.swing.JOptionPane.showInputDialog(this, "Nombre:");
        String apellido = javax.swing.JOptionPane.showInputDialog(this, "Apellido:");
        String email = javax.swing.JOptionPane.showInputDialog(this, "Email:");
        String telefono = javax.swing.JOptionPane.showInputDialog(this, "Telefono:");
        String fecha = javax.swing.JOptionPane.showInputDialog(this, "Fecha de ingreso (YYYY-MM-DD):");
        
        modelo.Funcionario f = new modelo.Funcionario();
        f.setCedula(cedula); 
        f.setNombre(nombre);
        f.setApellido(apellido);
        f.setEmail(email); 
        f.setTelefono(telefono);
        f.setFechaIngreso(fecha);
        
        try {
            dao.crear(f);
            javax.swing.JOptionPane.showMessageDialog(this, "Funcionario creado.");
            CargarTabla();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    
        int id = getIdSeleccionado();
        if (id == -1) return;
        
        int fila = tablaDatos.getSelectedRow();
        
        // Prellenamos con los valores actuales de la fila seleccionada
        String cedula = javax.swing.JOptionPane.showInputDialog(this, "Cedula:", tablaDatos.getValueAt(fila, 1));
        if (cedula == null) return;
        
        String nombre = javax.swing.JOptionPane.showInputDialog(this, "Nombre:", tablaDatos.getValueAt(fila, 2));
        String apellido = javax.swing.JOptionPane.showInputDialog(this, "Apellido:", tablaDatos.getValueAt(fila, 3));
        String email = javax.swing.JOptionPane.showInputDialog(this, "Email:", tablaDatos.getValueAt(fila, 4));
        String telefono = javax.swing.JOptionPane.showInputDialog(this, "Telefono:", tablaDatos.getValueAt(fila, 5));
        String fecha = javax.swing.JOptionPane.showInputDialog(this, "Fecha (YYYY-MM-DD):", tablaDatos.getValueAt(fila, 6));
        
        modelo.Funcionario f = new modelo.Funcionario();
        f.setId(id); 
        f.setCedula(cedula);
        f.setNombre(nombre);
        f.setApellido(apellido); 
        f.setEmail(email);
        f.setTelefono(telefono);
        f.setFechaIngreso(fecha);
        
        try {
            dao.actualizar(f);
            javax.swing.JOptionPane.showMessageDialog(this, "Funcionario actualizado.");
            CargarTabla();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       
        int id = getIdSeleccionado();
        if (id == -1) return;
        
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Eliminar este funcionario?", 
            "Confirmar", 
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                dao.eliminar(id);
                javax.swing.JOptionPane.showMessageDialog(this, "Funcionario eliminado.");
                CargarTabla();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        CargarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDatos;
    // End of variables declaration//GEN-END:variables
}
